"""
Django settings for mysite project.
Dev-friendly settings for local macOS (STATIC/MEDIA, templates, UA locale).
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# === Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Security ===
# ⚠️ DEV only. Don't use DEBUG=True or this secret in production.
SECRET_KEY = 'django-insecure-s3o=xixbekyz4=k3_gda-nf7&1xa-!-n%_cxq+l1cqpy$88qqh'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# === Applications ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # your app(s)
    'app_blog',
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

# === Templates ===
# By default uses app templates (APP_DIRS=True).
# Also supports a global templates/ folder at project root.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # e.g. BASE_DIR/templates/index.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# === Database (SQLite dev) ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === Password validators ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === i18n / l10n ===
LANGUAGE_CODE = 'uk'                 # українська локаль
TIME_ZONE = 'Europe/Kyiv'            # твоя часовa зона
USE_I18N = True
USE_TZ = True

# === Static files (CSS, JS, images served as "static") ===
# In dev, collected static can be served from STATICFILES_DIRS; for prod use collectstatic -> STATIC_ROOT.
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',             # put your dev assets here (optional, create folder if needed)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # where collectstatic will gather files for prod

# === Media (user uploads) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'      # uploaded files stored here

# === Default PK ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
